build:
	go build -o sssCheck/sssCheck sssCheck/sssCheck.go
	go build -o owner-client/owner owner-client/owner.go
	go build -o owner-client/client owner-client/client.go

clean:
	rm -rf sssCheck/sssCheck owner-client/owner owner-client/client sssCheck/output owner-client/output